### PR TITLE
Add MODEL_URI to env to download artifacts (e.g. Scaler) at runtime

### PR DESCRIPTION
**Pull request by pille321**
Add MODEL_URI to env to download artifacts (e.g. Scaler) at runtime

### CODE REVIEW

**Review by gerardcl — APPROVED** [review]
LGTM! will release it soon too 👍

**Comment by sklingel** [comment]
@pille321 can you explain why you need the MODEL_URI as and environment variable? It is passed over the provided mlflow deployment API and piped through into the template as a parameter, anyway.

**Comment by pille321** [comment]
@sklingel We train our model with scaled values and store the scalers next to the model in our S3-Bucket
```
mlflow.log_artifact('input_scaler.pkl')
mlflow.log_artifact('output_scaler.pkl')
```

To get valid predictions from our model after the deplyoment we have to scale the input and output values again. Therefore we need to download the *.pkl-Files from the S3-Bucket.

**Comment by sklingel** [comment]
Thank you @pille321 for answering this, tbh though, I don't understand how an environment variable will help you in that case given the rest of the logic from the [deploy_with_auth.yml](https://github.com/BIX-Digital/mlflow-openshift/pull/5/files#diff-5675be154fb9de0c71600f02233744f8f37c04bbc6bce8bcd6c92b5a73f25a6b).

However, though a more cleaner and mlflow integrated approach might be to either use something like https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html and save everything packed together with a coherent API. 
Or given your machine learning package does not support something like this, wrap your input/output scalar in a custom MLflow flavor (https://www.mlflow.org/docs/latest/models.html#id43).
In my experience both approaches work fine and are perhaps easier to handle and future-proof in terms of maintainability and scalability.

**Pull request merged**
